// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBHLQAHFfRYulD4fH4ZcHgWN0tc6jG8a8',
    appId: '1:222748934662:web:ec15e1a1f417c0f5227987',
    messagingSenderId: '222748934662',
    projectId: 'stok-takip-32df4',
    authDomain: 'stok-takip-32df4.firebaseapp.com',
    storageBucket: 'stok-takip-32df4.firebasestorage.app',
    measurementId: 'G-7MGC9Z9Z98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyTEP47SJdrc6k6-armg0JT9CLDwUU6W8',
    appId: '1:222748934662:android:6dc0705b3ec86738227987',
    messagingSenderId: '222748934662',
    projectId: 'stok-takip-32df4',
    storageBucket: 'stok-takip-32df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2vbpEZyA80wClrLaIofqV5_qn7wVu-Y',
    appId: '1:222748934662:ios:5dccd636255a3277227987',
    messagingSenderId: '222748934662',
    projectId: 'stok-takip-32df4',
    storageBucket: 'stok-takip-32df4.firebasestorage.app',
    iosBundleId: 'com.example.stokTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2vbpEZyA80wClrLaIofqV5_qn7wVu-Y',
    appId: '1:222748934662:ios:5dccd636255a3277227987',
    messagingSenderId: '222748934662',
    projectId: 'stok-takip-32df4',
    storageBucket: 'stok-takip-32df4.firebasestorage.app',
    iosBundleId: 'com.example.stokTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBHLQAHFfRYulD4fH4ZcHgWN0tc6jG8a8',
    appId: '1:222748934662:web:357db1f518e0d7d1227987',
    messagingSenderId: '222748934662',
    projectId: 'stok-takip-32df4',
    authDomain: 'stok-takip-32df4.firebaseapp.com',
    storageBucket: 'stok-takip-32df4.firebasestorage.app',
    measurementId: 'G-TBKTES6NZS',
  );
}
